### PR TITLE
Handle callback messages from preproposal contracts

### PR DESCRIPTION
**Pull request by ismellike**
https://github.com/DA0-DA0/dao-contracts/pull/634#issuecomment-1406904421

### CODE REVIEW

**Comment by 0xekez** [comment]
lg2m. @blue-note mind giving this a glance?

**Review by JakeHartnell — APPROVED** [review]

**Comment by JakeHartnell** [comment]
Failing lints, but otherwise this LGTM.

**Review by 0xekez — APPROVED** [review]

**Review by blue-note — APPROVED** [review]
looks good, thanks! merging a PR now that fixes the lint issue so you can rebase

**Comment by JakeHartnell** [comment]
Closing in favor of #636 to fix the linting errors.

**Comment by JakeHartnell** [comment]
Thank you for this! :pray:

**Pull request closed without merging**
