### PR TITLE
Finish cw-orch integration

### PR DESCRIPTION
**Pull request by ismellike**
Continuation of https://github.com/DA0-DA0/dao-contracts/pull/831

- Fixes merge conflicts
- Fixes lints
- Adds `wasm_test` feature to test_contracts/tests.rs to avoid wasm build from basic.yml
- Fixes schema diff
- Adds `#[cfg(not(target_arch = "wasm32"))]` to cw_orch contracts for wasm compilation in basic.yml
- Bumps workspace optimizer version to 0.16.0

Bonus:
- Updates `just lint` to match basic.yml commands

### CODE REVIEW

**Comment by JakeHartnell** [comment]
Looking good, just need to get CI to pass. 💪

**Comment by JakeHartnell** [comment]
Looks like to fix integration tests we just need to bump the rust version in CI?

```
error: package `prost-derive v0.12.6` cannot be built because it requires rustc 1.70 or newer, while the currently active rustc version is 1.69.0-nightly
Either upgrade to rustc 1.70 or newer, or use
cargo update -p prost-derive@0.12.6 --precise ver
where `ver` is the latest version of `prost-derive` supporting rustc 1.69.0-nightly
error: Recipe `integration-test` failed on line 21 with exit code 101
Error: Process completed with exit code 101.
```

**Comment by noahsaso** [comment]
> Looks like to fix integration tests we just need to bump the rust version in CI?
> 
> ```
> error: package `prost-derive v0.12.6` cannot be built because it requires rustc 1.70 or newer, while the currently active rustc version is 1.69.0-nightly
> Either upgrade to rustc 1.70 or newer, or use
> cargo update -p prost-derive@0.12.6 --precise ver
> where `ver` is the latest version of `prost-derive` supporting rustc 1.69.0-nightly
> error: Recipe `integration-test` failed on line 21 with exit code 101
> Error: Process completed with exit code 101.
> ```

we're fixing this over in #859

update: just merged

**Comment by ismellike** [comment]
@hard-nett  is gonna add some stuff later today too

**Comment by ismellike** [comment]
Ok we should be good now.
@hard-nett latest changes were to establish a centralized framework for testing in /scripts
https://orchestrator.abstract.money/setup/workspace/setup.html#final-project-structure

**Comment by ismellike** [comment]
any suggestions for fixing the test-tube integration tests running out of space?

**Comment by hard-nett** [comment]
> any suggestions for fixing the test-tube integration tests running out of space?

not too sure for getting around the ci vm error, but  would you agree we can now replace the test-tube logic with cw-orch entirely?

**Comment by ismellike** [comment]
> > any suggestions for fixing the test-tube integration tests running out of space?
> 
> not too sure for getting around the ci vm error, but  would you agree we can now replace the test-tube logic with cw-orch entirely?

Definitely. This should help us get everything on the same version as well, and it should help with the CI storage issue.

**Pull request merged**
