### PR TITLE
Extend `cw-vesting` to allow for staking in DAOs

### LINKED ISSUE #779: `cw-vesting` should allow for staking in DAOs
Currently, `cw-vesting` supports staking tokens natively on Cosmos chains, we need something similar but designed for staking in token DAOs.

As a user who receives vested tokens from a DAO, I would like to be able to stake those tokens to participate in governance.

### PR DESCRIPTION
**Pull request by JakeHartnell**
Closes #779

This topic keeps coming up in spaces and I wanted to explore how difficult it would be. This PR is a strawman solution (couldn't help myself :joy:). DO NOT MERGE.

Some observations:
- Need to restrict which staking contracts a vesting contract can stake with as that could be a way to sneak out unvested funds if the staking contract is not trusted.
- Not supporting the ability to propose drastically simplifies things as we don't have to worry about deposits getting refunded.
- Not supporting cw20 greatly simplifies things, but we may want to add support for that for use with the $DAO token?
- Doesn't really impact core logic too much and so should be relatively safe and cheep to audit.
- Frontend would certainly require work with this approach... but hard to imagine an approach where that wouldn't be the case.

### CODE REVIEW

**Comment by noahsaso** [comment]
Features derived from list above and discussion in Monday call:
- Mutable allowlist of contracts the staking contract can interact with (should be instantiated with the voting module / staking contract)
- Ability to passthrough wasm messages to the allowlisted contracts, so that the owner can send returned deposits back to themself for example
- Flag to enable or disable staking (maybe just via the allowlist being empty or not)
- Multiplier for voting power derived from remaining vesting
- Require proposal deposits to be already vested (i.e. liquid and transferrable)

**Comment by JakeHartnell** [comment]
Related issues we may also want to consider when working on this:
- https://github.com/DA0-DA0/dao-contracts/issues/710
- https://github.com/DA0-DA0/dao-contracts/issues/677

**Comment by JakeHartnell** [comment]
Limits on voting power for vested tokens could be achieved with #746.

**Comment by noahsaso** [comment]
Closing as this is not the design we are going to pursue to add voting support for vesting tokens.

**Pull request closed without merging**
