### PR TITLE
Switch to using cosmwasm-typescript-gen

### PR DESCRIPTION
**Pull request by de-husk**
I wanted to get the latest ibc interface changes. Looks like there are other changes here as well. 

closes: https://github.com/DA0-DA0/dao-contracts/issues/364

### CODE REVIEW

**Comment by JakeHartnell** [comment]
Hmmmmm, that reminds me... we should replace this with @pyramation's generated code. It's a bit nicer.

**Comment by Samangan** [comment]
> Hmmmmm, this reminds me... we should replace this with @pyramation's generated code. It's a bit nicer.

Awesome! I'll switch over to using this: https://github.com/pyramation/cosmwasm-typescript-gen

**Comment by de-husk** [comment]
I switched everything over to using @pyramation's codegen, and its much simpler now :tada:

Im running into a couple of issues that we will need to fix before merging though: 

We missing some enums which is already tracked [here](https://github.com/pyramation/cosmwasm-typescript-gen/issues/10).
```
contracts/cw-core/CwCoreContract.ts:361:11 - error TS2304: Cannot find name 'CosmosMsg_for_Empty'.

361     msgs: CosmosMsg_for_Empty[];
              ~~~~~~~~~~~~~~~~~~~
```

Im running into an error when trying to generate the ts files for a few contracts:
```
$  node_modules/cosmwasm-typescript-gen/main/cosmwasm-typescript-gen.js generate     --schema ./contracts/cw-named-groups/schema     --out ./contracts/cw-named-groups     --name cw-named-groups

/Users/harry/cosmos/dao-contracts/types/node_modules/wasm-ast-types/main/wasm.js:70
      throw new Error('what is type: ' + type);
            ^

Error: what is type: array
    at getType (/Users/harry/cosmos/dao-contracts/types/node_modules/wasm-ast-types/main/wasm.js:70:13)
    at getPropertyType (/Users/harry/cosmos/dao-contracts/types/node_modules/wasm-ast-types/main/wasm.js:134:12)
    at /Users/harry/cosmos/dao-contracts/types/node_modules/wasm-ast-types/main/wasm.js:283:28
    at Array.map (<anonymous>)
    at createTypedObjectParams (/Users/harry/cosmos/dao-contracts/types/node_modules/wasm-ast-types/main/wasm.js:282:26)
    at createPropertyFunctionWithObjectParamsForExec (/Users/harry/cosmos/dao-contracts/types/node_modules/wasm-ast-types/main/wasm.js:312:13)
    at /Users/harry/cosmos/dao-contracts/types/node_modules/wasm-ast-types/main/wasm.js:246:12
    at Array.map (<anonymous>)
    at Object.createExecuteInterface (/Users/harry/cosmos/dao-contracts/types/node_modules/wasm-ast-types/main/wasm.js:243:59)
    at _callee$ (/Users/harry/cosmos/dao-contracts/types/node_modules/cosmwasm-typescript-gen/main/generate.js:113:29)

Node.js v18.0.0
```

Ill dig deeper into this error and make an issue.

**Comment by de-husk** [comment]
Coming back to this, [that error](https://github.com/pyramation/cosmwasm-typescript-gen/blob/master/packages/wasm-ast-types/src/wasm.ts#L57 ) is happening on [this ExecuteMsg](https://github.com/DA0-DA0/dao-contracts/blob/main/contracts/cw-named-groups/schema/execute_msg.json#L5-L42). When that block of code is removed it generates the types without error. 

I made an [issue](https://github.com/pyramation/cosmwasm-typescript-gen/issues/17).

**Comment by de-husk** [comment]
Thanks to the quick work of @pyramation, `yarn codegen` is now running without errors. 

Ill work on fixing up the remaining non, missing enum errors later.

**Review by JakeHartnell — APPROVED** [review]
Nice progress! Looks like this will close #364.

**Review by ezekiiel — APPROVED** [review]
Awesome! Thank you.

**Pull request merged**
