### PR TITLE
Add proposal hooks macro

### LINKED ISSUE #459: ProposalHookMsg variants should be derivable via a macro
In the `proposal-hooks` package we provide an enum with variants that must be implemented by hook receivers. We should provide a macro which will automatically add these to an existing execute message.

### PR DESCRIPTION
**Pull request by Callum-A**
Closes #459 
- Adds a macro to derive proposal hooks
- Adds a macro to derive vote hooks

### CODE REVIEW

**Comment by 0xekez** [comment]
looks great :) just needs a rebase on the new naming stuff. sorry to rug with that

**Comment by 0xekez** [comment]
gonna get rugged by this too if we don't rebase and merge this soon: https://github.com/DA0-DA0/dao-contracts/pull/516

**Review by JakeHartnell — APPROVED** [review]
LGTM

**Comment by JakeHartnell** [comment]
@0xekez, think this one is good to go now?

**Pull request closed without merging**
