### PR TITLE
Docs: (Readme)

### PR DESCRIPTION
**Pull request by Radovenchyk**
Fixed some inaccuracies

### CODE REVIEW

**Comment by noahsaso** [comment]
thanks for this! can you rebase on the latest development and force push?

**Comment by Radovenchyk** [comment]
I'm sorry, my friend, but I don't know how to do it. I'm just learning

**Comment by noahsaso** [comment]
> I'm sorry, my friend, but I don't know how to do it. I'm just learning

all good, i took care of it :)

what i did was:
```
git remote add radovenchyk https://github.com/Radovenchyk/dao-contracts.git
git fetch radovenchyk
git checkout patch-1
git rebase development
git push -f
```

**Review by noahsaso — APPROVED** [review]

**Comment by Radovenchyk** [comment]
Thank you for the clarification

**Pull request merged**
